//! Embeds the agent skills and the project templates into the binary.
//!
//! A published binary is the only thing a user downloads, so the files a project
//! needs at initialization have to travel inside it. The contents are written
//! into the generated source as string literals rather than `include_str!` paths,
//! so the build does not depend on where the repository sits on disk.

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

const EMBEDDED_ROOTS: [&str; 2] = ["skill-src", "templates"];

fn main() {
    let manifest_root = PathBuf::from(
        env::var("CARGO_MANIFEST_DIR").expect("cargo sets CARGO_MANIFEST_DIR for build scripts"),
    );
    let mut assets = Vec::new();
    for root in EMBEDDED_ROOTS {
        let path = manifest_root.join(root);
        println!("cargo:rerun-if-changed={}", path.display());
        collect(&path, &manifest_root, &mut assets);
    }
    assets.sort();

    let mut generated = String::from(
        "// Generated by build.rs. Do not edit.\n\
         /// Repository-relative path and contents of every embedded asset.\n\
         pub static EMBEDDED_ASSETS: &[(&str, &str)] = &[\n",
    );
    for (path, contents) in &assets {
        writeln!(generated, "    ({path:?}, {contents:?}),").expect("writing to a String");
    }
    generated.push_str("];\n");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("cargo sets OUT_DIR for build scripts"));
    fs::write(out_dir.join("embedded_assets.rs"), generated)
        .expect("cannot write the generated asset table");
}

fn collect(directory: &Path, manifest_root: &Path, assets: &mut Vec<(String, String)>) {
    let entries = match fs::read_dir(directory) {
        Ok(entries) => entries,
        Err(error) => panic!("cannot read {}: {error}", directory.display()),
    };
    for entry in entries {
        let entry = entry.expect("cannot read a directory entry");
        let path = entry.path();
        println!("cargo:rerun-if-changed={}", path.display());
        if path.is_dir() {
            collect(&path, manifest_root, assets);
            continue;
        }
        let relative = path
            .strip_prefix(manifest_root)
            .expect("embedded assets live under the manifest root")
            .to_str()
            .expect("embedded asset paths are UTF-8")
            .replace('\\', "/");
        let contents = fs::read_to_string(&path)
            .unwrap_or_else(|error| panic!("cannot read {}: {error}", path.display()));
        assets.push((relative, contents));
    }
}
